export const MOOD_MAP = {
  Sleepy: {
    valence: 0.3,
    energy: 0.2,
    danceability: 0.3,
    tempo: 70,
    acousticness: 0.8,
    seed_genres: ['sleep', 'ambient'],
  },
  Motivated: {
    valence: 0.8,
    energy: 0.9,
    danceability: 0.7,
    tempo: 140,
    acousticness: 0.1,
    seed_genres: ['workout', 'power-pop'],
  },
  Emotional: {
    valence: 0.2,
    energy: 0.4,
    danceability: 0.3,
    tempo: 80,
    acousticness: 0.6,
    seed_genres: ['sad', 'emo', 'singer-songwriter'],
  },
  Happy: {
    valence: 0.9,
    energy: 0.7,
    danceability: 0.8,
    tempo: 120,
    acousticness: 0.2,
    seed_genres: ['pop', 'happy'],
  },
  Chill: {
    valence: 0.6,
    energy: 0.3,
    danceability: 0.5,
    tempo: 90,
    acousticness: 0.5,
    seed_genres: ['chill', 'lo-fi'],
  },
  Party: {
    valence: 0.8,
    energy: 0.9,
    danceability: 0.9,
    tempo: 128,
    acousticness: 0.0,
    seed_genres: ['dance', 'edm', 'party'],
  },
  Angry: {
    valence: 0.2,
    energy: 0.9,
    danceability: 0.5,
    tempo: 160,
    acousticness: 0.0,
    seed_genres: ['metal', 'rock', 'punk'],
  },
  Focus: {
    valence: 0.5,
    energy: 0.5,
    danceability: 0.3,
    tempo: 100,
    acousticness: 0.4,
    seed_genres: ['study', 'focus', 'classical'],
  },
  Sad: {
    valence: 0.1,
    energy: 0.2,
    danceability: 0.2,
    tempo: 65,
    acousticness: 0.7,
    seed_genres: ['sad', 'blues', 'soul'],
  },
}

export default MOOD_MAP
